# Generated by Django 2.2.14 on 2020-08-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='email')),
                ('date_entry', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('dir_image', models.FileField(blank=True, max_length=250, null=True, upload_to='imagenes/')),
                ('user_active', models.BooleanField(default=True)),
                ('user_manager', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
